Add support for pretrained encoders and transformed data
koaning/simsity pull request #13
Opened 2021-10-29 01:59 UTC by gclen

First of all this project looks great! I've taken an initial stab at #12 and also tried to add support querying data that has already been transformed. If you have data that you've already transformed (e.g. a UMAP embedding), you probably don't want to rerun encoder.transform again. In this case you want to index the transformed data and query it directly.

This is just a first crack so happy to incorporate any feedback you might have!

2021-10-30 19:44 UTC, gclen commented
Apologies for not commenting on the issue beforehand. I think it's a fair point about ```check_is_fitted``` and how it won't work for everything. 

I think the refit parameter should go in the ```Service()``` call. I think there should also be a parameter somewhere to avoid calling ```.transform()``` if the data has already been transformed. Do you think it is worth adding an additional parameter to ```Service()``` and keeping the ```indexed_from_transformed_data``` method?

2021-10-31 09:06 UTC, koaning commented
I think preventing a `transfrom()` is fair, but the solution would be to have an `Identity()` transformer that just keeps the data as-is. This would also make a great default value for the encoder. I added a separate issue for this over at https://github.com/koaning/simsity/issues/14.

2021-10-31 09:08 UTC, koaning commented
Let's add a `refit` to `Service()` then. This parameter should prevent the `.fit()` step from happening in the transformer. This would pass on some responsibility to the end-user, which means that we may want to catch some errors and proxy them in a meaningful way. Something like "Are you sure the encoder is trained?" in the error message would go a long way. 

@gclen would you want to pick this up by changing this PR? I'd also be fine with the creation of a new one.

2021-11-01 12:50 UTC, gclen commented
I can pick this up (hopefully in the next couple days).

2021-11-03 00:21 UTC, gclen commented
I've made the changes we talked about if you want to take another look.

2021-11-03 06:43 UTC, koaning commented on simsity/service.py
> +            self._trained = True
Wouldn't this be more succinct:

```python
self._trained = not refit
```

2021-11-03 06:46 UTC, koaning commented on simsity/service.py
> +            data = self.encoder.fit_transform(subset)
I think we're about to omit another `else` statement here to keep things succinct. 

```python
if not self._trained:
    self.encoder.fit(subset)

try:
    data = self.encoder.transform(subset)
except Exception as e:
    warnings.warn("Encountered error using pretrained encoder. Are you sure it is trained?")
    raise e
```

2021-11-03 06:47 UTC, koaning commented on simsity/service.py
> +            raise RuntimeError("Cannot query, Service is not trained.")
Nice catch 👍

2021-11-03 06:52 UTC, koaning requested changes
I think there's an opportunity to make the code a bit more succinct. Once those small comments are addressed I'll happily merge it in 👍

2021-11-03 06:52 UTC, koaning commented
Once merged, this PR fill fix https://github.com/koaning/simsity/issues/12.

2021-11-03 21:03 UTC, gclen commented
Done.

2021-11-03 22:06 UTC, koaning commented
There seem to be merge conflicts now that the other PR went in. Could you resolve it? If so I'll merge this in and make a new release tomorrow.

2021-11-03 22:41 UTC, gclen commented
Should be fixed now 👍

2021-11-04 10:47 UTC, merged